//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.06.09 at 09:24:26 PM CEST 
//


package com.users.model.rjesenje;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="id"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}long"&gt;
 *               &lt;minInclusive value="1"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="id_zahtjeva"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}long"&gt;
 *               &lt;minInclusive value="1"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="tip_zahtjeva" type="{http://users.com/model/rjesenje}TTip_Zahtjeva"/&gt;
 *         &lt;element name="slucaj" type="{http://users.com/model/rjesenje}TSlucaj"/&gt;
 *         &lt;element name="datum" type="{http://www.w3.org/2001/XMLSchema}date"/&gt;
 *         &lt;element name="ime_sluzbenika" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="prezime_sluzbenika" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;choice&gt;
 *           &lt;element name="sifra" type="{http://www.w3.org/2001/XMLSchema}positiveInteger"/&gt;
 *           &lt;element name="obrazlozenje" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;/choice&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "id",
    "idZahtjeva",
    "tipZahtjeva",
    "slucaj",
    "datum",
    "imeSluzbenika",
    "prezimeSluzbenika",
    "sifra",
    "obrazlozenje"
})
@XmlRootElement(name = "rjesenje")
public class Rjesenje {

    protected long id;
    @XmlElement(name = "id_zahtjeva")
    protected long idZahtjeva;
    @XmlElement(name = "tip_zahtjeva", required = true)
    @XmlSchemaType(name = "string")
    protected TTipZahtjeva tipZahtjeva;
    @XmlElement(required = true)
    @XmlSchemaType(name = "string")
    protected TSlucaj slucaj;
    @XmlElement(required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar datum;
    @XmlElement(name = "ime_sluzbenika", required = true)
    protected String imeSluzbenika;
    @XmlElement(name = "prezime_sluzbenika", required = true)
    protected String prezimeSluzbenika;
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger sifra;
    protected String obrazlozenje;

    /**
     * Gets the value of the id property.
     * 
     */
    public long getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     */
    public void setId(long value) {
        this.id = value;
    }

    /**
     * Gets the value of the idZahtjeva property.
     * 
     */
    public long getIdZahtjeva() {
        return idZahtjeva;
    }

    /**
     * Sets the value of the idZahtjeva property.
     * 
     */
    public void setIdZahtjeva(long value) {
        this.idZahtjeva = value;
    }

    /**
     * Gets the value of the tipZahtjeva property.
     * 
     * @return
     *     possible object is
     *     {@link TTipZahtjeva }
     *     
     */
    public TTipZahtjeva getTipZahtjeva() {
        return tipZahtjeva;
    }

    /**
     * Sets the value of the tipZahtjeva property.
     * 
     * @param value
     *     allowed object is
     *     {@link TTipZahtjeva }
     *     
     */
    public void setTipZahtjeva(TTipZahtjeva value) {
        this.tipZahtjeva = value;
    }

    /**
     * Gets the value of the slucaj property.
     * 
     * @return
     *     possible object is
     *     {@link TSlucaj }
     *     
     */
    public TSlucaj getSlucaj() {
        return slucaj;
    }

    /**
     * Sets the value of the slucaj property.
     * 
     * @param value
     *     allowed object is
     *     {@link TSlucaj }
     *     
     */
    public void setSlucaj(TSlucaj value) {
        this.slucaj = value;
    }

    /**
     * Gets the value of the datum property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDatum() {
        return datum;
    }

    /**
     * Sets the value of the datum property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDatum(XMLGregorianCalendar value) {
        this.datum = value;
    }

    /**
     * Gets the value of the imeSluzbenika property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getImeSluzbenika() {
        return imeSluzbenika;
    }

    /**
     * Sets the value of the imeSluzbenika property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setImeSluzbenika(String value) {
        this.imeSluzbenika = value;
    }

    /**
     * Gets the value of the prezimeSluzbenika property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPrezimeSluzbenika() {
        return prezimeSluzbenika;
    }

    /**
     * Sets the value of the prezimeSluzbenika property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPrezimeSluzbenika(String value) {
        this.prezimeSluzbenika = value;
    }

    /**
     * Gets the value of the sifra property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getSifra() {
        return sifra;
    }

    /**
     * Sets the value of the sifra property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setSifra(BigInteger value) {
        this.sifra = value;
    }

    /**
     * Gets the value of the obrazlozenje property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getObrazlozenje() {
        return obrazlozenje;
    }

    /**
     * Sets the value of the obrazlozenje property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setObrazlozenje(String value) {
        this.obrazlozenje = value;
    }

}
