//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.01.18 at 06:29:29 PM CET 
//


package com.users.model.rjesenje;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TTip_Zahtjeva.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="TTip_Zahtjeva"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="A1"/&gt;
 *     &lt;enumeration value="P1"/&gt;
 *     &lt;enumeration value="Z1"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "TTip_Zahtjeva")
@XmlEnum
public enum TTipZahtjeva {

    @XmlEnumValue("A1")
    A_1("A1"),
    @XmlEnumValue("P1")
    P_1("P1"),
    @XmlEnumValue("Z1")
    Z_1("Z1");
    private final String value;

    TTipZahtjeva(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static TTipZahtjeva fromValue(String v) {
        for (TTipZahtjeva c: TTipZahtjeva.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
