//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.11.30 at 01:01:54 по подне CET 
//


package com.euprava.euprava.model.a1Sertifikat;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Forma_Zapisa.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="Forma_Zapisa">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="Pisana"/>
 *     &lt;enumeration value="Audio"/>
 *     &lt;enumeration value="Vizuelna"/>
 *     &lt;enumeration value="AudioVizuelna"/>
 *     &lt;enumeration value="Opticki Disk"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "Forma_Zapisa")
@XmlEnum
public enum FormaZapisa {

    @XmlEnumValue("Pisana")
    PISANA("Pisana"),
    @XmlEnumValue("Audio")
    AUDIO("Audio"),
    @XmlEnumValue("Vizuelna")
    VIZUELNA("Vizuelna"),
    @XmlEnumValue("AudioVizuelna")
    AUDIO_VIZUELNA("AudioVizuelna"),
    @XmlEnumValue("Opticki Disk")
    OPTICKI_DISK("Opticki Disk");
    private final String value;

    FormaZapisa(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static FormaZapisa fromValue(String v) {
        for (FormaZapisa c: FormaZapisa.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
