//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.11.30 at 01:01:54 по подне CET 
//


package com.euprava.euprava.model.a1Sertifikat;

import com.euprava.*;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.euprava package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.euprava
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link TPreminuliAutor }
     * 
     */
    public TPreminuliAutor createTPreminuliAutor() {
        return new TPreminuliAutor();
    }

    /**
     * Create an instance of {@link TOsoba }
     * 
     */
    public TOsoba createTOsoba() {
        return new TOsoba();
    }

    /**
     * Create an instance of {@link TDjelo }
     * 
     */
    public TDjelo createTDjelo() {
        return new TDjelo();
    }

    /**
     * Create an instance of {@link TPravniPodnosilac }
     * 
     */
    public TPravniPodnosilac createTPravniPodnosilac() {
        return new TPravniPodnosilac();
    }

    /**
     * Create an instance of {@link Adresa }
     * 
     */
    public Adresa createAdresa() {
        return new Adresa();
    }

    /**
     * Create an instance of {@link ObrazacA1 }
     * 
     */
    public ObrazacA1 createObrazacA1() {
        return new ObrazacA1();
    }

    /**
     * Create an instance of {@link TDjelo.PodaciAutor }
     * 
     */
    public TDjelo.PodaciAutor createTDjeloPodaciAutor() {
        return new TDjelo.PodaciAutor();
    }

    /**
     * Create an instance of {@link TFizickiPodnosilac }
     * 
     */
    public TFizickiPodnosilac createTFizickiPodnosilac() {
        return new TFizickiPodnosilac();
    }

    /**
     * Create an instance of {@link TStranoDrzavljanstvo }
     * 
     */
    public TStranoDrzavljanstvo createTStranoDrzavljanstvo() {
        return new TStranoDrzavljanstvo();
    }

    /**
     * Create an instance of {@link TZiviAutor }
     * 
     */
    public TZiviAutor createTZiviAutor() {
        return new TZiviAutor();
    }

    /**
     * Create an instance of {@link TDomaceDrzavljanstvo }
     * 
     */
    public TDomaceDrzavljanstvo createTDomaceDrzavljanstvo() {
        return new TDomaceDrzavljanstvo();
    }

    /**
     * Create an instance of {@link TDjelo.PodaciOriginalnoDjelo }
     * 
     */
    public TDjelo.PodaciOriginalnoDjelo createTDjeloPodaciOriginalnoDjelo() {
        return new TDjelo.PodaciOriginalnoDjelo();
    }

}
