//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.01.15 at 02:41:52 PM CET 
//


package com.euprava.p1.model;

import jakarta.xml.bind.annotation.*;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Na_srpskom" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="Na_engleskom" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "naSrpskom",
    "naEngleskom"
})
@XmlRootElement(name = "Naziv_pronalaska")
public class NazivPronalaska {

    @XmlElement(name = "Na_srpskom", required = true)
    protected String naSrpskom;
    @XmlElement(name = "Na_engleskom", required = true)
    protected String naEngleskom;

    /**
     * Gets the value of the naSrpskom property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNaSrpskom() {
        return naSrpskom;
    }

    /**
     * Sets the value of the naSrpskom property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNaSrpskom(String value) {
        this.naSrpskom = value;
    }

    /**
     * Gets the value of the naEngleskom property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNaEngleskom() {
        return naEngleskom;
    }

    /**
     * Sets the value of the naEngleskom property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNaEngleskom(String value) {
        this.naEngleskom = value;
    }

}
