//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.12.12 at 11:21:11 PM CET 
//


package com.euprava.p1.model;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.euprava.p1.model package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.euprava.p1.model
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ObrazacP1 }
     * 
     */
    public ObrazacP1 createObrazacP1() {
        return new ObrazacP1();
    }

    /**
     * Create an instance of {@link PopunjavaZavod }
     * 
     */
    public PopunjavaZavod createPopunjavaZavod() {
        return new PopunjavaZavod();
    }

    /**
     * Create an instance of {@link ZahtevZaPriznanjePatenta }
     * 
     */
    public ZahtevZaPriznanjePatenta createZahtevZaPriznanjePatenta() {
        return new ZahtevZaPriznanjePatenta();
    }

    /**
     * Create an instance of {@link NazivPronalaska }
     * 
     */
    public NazivPronalaska createNazivPronalaska() {
        return new NazivPronalaska();
    }

    /**
     * Create an instance of {@link PodnosilacPrijave }
     * 
     */
    public PodnosilacPrijave createPodnosilacPrijave() {
        return new PodnosilacPrijave();
    }

    /**
     * Create an instance of {@link Pronalazac }
     * 
     */
    public Pronalazac createPronalazac() {
        return new Pronalazac();
    }

    /**
     * Create an instance of {@link TFizickiPodnosilac }
     * 
     */
    public TFizickiPodnosilac createTFizickiPodnosilac() {
        return new TFizickiPodnosilac();
    }

    /**
     * Create an instance of {@link PunomocnikIliPredstavnik }
     * 
     */
    public PunomocnikIliPredstavnik createPunomocnikIliPredstavnik() {
        return new PunomocnikIliPredstavnik();
    }

    /**
     * Create an instance of {@link TAdresaUnutarDrzave }
     * 
     */
    public TAdresaUnutarDrzave createTAdresaUnutarDrzave() {
        return new TAdresaUnutarDrzave();
    }

    /**
     * Create an instance of {@link PovezanaPrijava }
     * 
     */
    public PovezanaPrijava createPovezanaPrijava() {
        return new PovezanaPrijava();
    }

    /**
     * Create an instance of {@link ZahtevZaPriznanjePravaPrvenstva }
     * 
     */
    public ZahtevZaPriznanjePravaPrvenstva createZahtevZaPriznanjePravaPrvenstva() {
        return new ZahtevZaPriznanjePravaPrvenstva();
    }

    /**
     * Create an instance of {@link RanijaPrijava }
     * 
     */
    public RanijaPrijava createRanijaPrijava() {
        return new RanijaPrijava();
    }

    /**
     * Create an instance of {@link TPunaAdresa }
     * 
     */
    public TPunaAdresa createTPunaAdresa() {
        return new TPunaAdresa();
    }

    /**
     * Create an instance of {@link TLiceKontakt }
     * 
     */
    public TLiceKontakt createTLiceKontakt() {
        return new TLiceKontakt();
    }

    /**
     * Create an instance of {@link TPodnosilacKontakt }
     * 
     */
    public TPodnosilacKontakt createTPodnosilacKontakt() {
        return new TPodnosilacKontakt();
    }

    /**
     * Create an instance of {@link TFizickoLice }
     * 
     */
    public TFizickoLice createTFizickoLice() {
        return new TFizickoLice();
    }

    /**
     * Create an instance of {@link TPravnoLice }
     * 
     */
    public TPravnoLice createTPravnoLice() {
        return new TPravnoLice();
    }

    /**
     * Create an instance of {@link TPravniPodnosilac }
     * 
     */
    public TPravniPodnosilac createTPravniPodnosilac() {
        return new TPravniPodnosilac();
    }

}
