//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.02.05 at 08:29:53 AM CET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://p1.euprava.com/model", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.euprava.p1.model;
