//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.01.15 at 02:41:52 PM CET 
//

@jakarta.xml.bind.annotation.XmlSchema(namespace = "http://euprava.com/p1/model", elementFormDefault = jakarta.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.euprava.p1.model;
