//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.01.21 at 01:34:35 AM CET 
//


package com.euprava.p1.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TPodnosilac complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TPodnosilac"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://euprava.com/p1/model}TLice"&gt;
 *       &lt;attribute name="pronalazac" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TPodnosilac")
@XmlSeeAlso({
    TFizickiPodnosilac.class,
    TPravniPodnosilac.class
})
public abstract class TPodnosilac
    extends TLice
{

    @XmlAttribute(name = "pronalazac", required = true)
    protected boolean pronalazac;

    /**
     * Gets the value of the pronalazac property.
     * 
     */
    public boolean isPronalazac() {
        return pronalazac;
    }

    /**
     * Sets the value of the pronalazac property.
     * 
     */
    public void setPronalazac(boolean value) {
        this.pronalazac = value;
    }

}
