//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.01.22 at 12:41:26 PM CET 
//


package com.euprava.p1.model;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TTip_punomocnika.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="TTip_punomocnika"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="Punomocnik_za_zastupanje"/&gt;
 *     &lt;enumeration value="Punomocnik_za_prijem_pismena"/&gt;
 *     &lt;enumeration value="Zajednicki_predstavnik"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "TTip_punomocnika")
@XmlEnum
public enum TTipPunomocnika {

    @XmlEnumValue("Punomocnik_za_zastupanje")
    PUNOMOCNIK_ZA_ZASTUPANJE("Punomocnik_za_zastupanje"),
    @XmlEnumValue("Punomocnik_za_prijem_pismena")
    PUNOMOCNIK_ZA_PRIJEM_PISMENA("Punomocnik_za_prijem_pismena"),
    @XmlEnumValue("Zajednicki_predstavnik")
    ZAJEDNICKI_PREDSTAVNIK("Zajednicki_predstavnik");
    private final String value;

    TTipPunomocnika(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static TTipPunomocnika fromValue(String v) {
        for (TTipPunomocnika c: TTipPunomocnika.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
