//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.02.05 at 08:29:53 AM CET 
//


package com.euprava.p1.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{http://p1.euprava.com/model}Naziv_pronalaska"/&gt;
 *         &lt;element name="Podnosilac" type="{http://p1.euprava.com/model}TPodnosilac"/&gt;
 *         &lt;element name="Pronalazac" type="{http://p1.euprava.com/model}TPronalazac" minOccurs="0"/&gt;
 *         &lt;element name="Punomocnik" type="{http://p1.euprava.com/model}TPunomocnik" minOccurs="0"/&gt;
 *         &lt;element name="Adresa_za_dostavljanje" type="{http://p1.euprava.com/model}TAdresa" minOccurs="0"/&gt;
 *         &lt;element name="Nacin_dostavljanja" type="{http://p1.euprava.com/model}TNacin_dostavljanja"/&gt;
 *         &lt;element ref="{http://p1.euprava.com/model}Povezana_prijava" minOccurs="0"/&gt;
 *         &lt;element ref="{http://p1.euprava.com/model}Zahtev_za_priznanje_prava_prvenstva" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "nazivPronalaska",
    "podnosilac",
    "pronalazac",
    "punomocnik",
    "adresaZaDostavljanje",
    "nacinDostavljanja",
    "povezanaPrijava",
    "zahtevZaPriznanjePravaPrvenstva"
})
@XmlRootElement(name = "Zahtev_za_priznanje_patenta")
public class ZahtevZaPriznanjePatenta {

    @XmlElement(name = "Naziv_pronalaska", required = true)
    protected NazivPronalaska nazivPronalaska;
    @XmlElement(name = "Podnosilac", required = true)
    protected TPodnosilac podnosilac;
    @XmlElement(name = "Pronalazac")
    protected TPronalazac pronalazac;
    @XmlElement(name = "Punomocnik")
    protected TPunomocnik punomocnik;
    @XmlElement(name = "Adresa_za_dostavljanje")
    protected TAdresa adresaZaDostavljanje;
    @XmlElement(name = "Nacin_dostavljanja", required = true)
    @XmlSchemaType(name = "string")
    protected TNacinDostavljanja nacinDostavljanja;
    @XmlElement(name = "Povezana_prijava")
    protected PovezanaPrijava povezanaPrijava;
    @XmlElement(name = "Zahtev_za_priznanje_prava_prvenstva")
    protected ZahtevZaPriznanjePravaPrvenstva zahtevZaPriznanjePravaPrvenstva;

    /**
     * Gets the value of the nazivPronalaska property.
     * 
     * @return
     *     possible object is
     *     {@link NazivPronalaska }
     *     
     */
    public NazivPronalaska getNazivPronalaska() {
        return nazivPronalaska;
    }

    /**
     * Sets the value of the nazivPronalaska property.
     * 
     * @param value
     *     allowed object is
     *     {@link NazivPronalaska }
     *     
     */
    public void setNazivPronalaska(NazivPronalaska value) {
        this.nazivPronalaska = value;
    }

    /**
     * Gets the value of the podnosilac property.
     * 
     * @return
     *     possible object is
     *     {@link TPodnosilac }
     *     
     */
    public TPodnosilac getPodnosilac() {
        return podnosilac;
    }

    /**
     * Sets the value of the podnosilac property.
     * 
     * @param value
     *     allowed object is
     *     {@link TPodnosilac }
     *     
     */
    public void setPodnosilac(TPodnosilac value) {
        this.podnosilac = value;
    }

    /**
     * Gets the value of the pronalazac property.
     * 
     * @return
     *     possible object is
     *     {@link TPronalazac }
     *     
     */
    public TPronalazac getPronalazac() {
        return pronalazac;
    }

    /**
     * Sets the value of the pronalazac property.
     * 
     * @param value
     *     allowed object is
     *     {@link TPronalazac }
     *     
     */
    public void setPronalazac(TPronalazac value) {
        this.pronalazac = value;
    }

    /**
     * Gets the value of the punomocnik property.
     * 
     * @return
     *     possible object is
     *     {@link TPunomocnik }
     *     
     */
    public TPunomocnik getPunomocnik() {
        return punomocnik;
    }

    /**
     * Sets the value of the punomocnik property.
     * 
     * @param value
     *     allowed object is
     *     {@link TPunomocnik }
     *     
     */
    public void setPunomocnik(TPunomocnik value) {
        this.punomocnik = value;
    }

    /**
     * Gets the value of the adresaZaDostavljanje property.
     * 
     * @return
     *     possible object is
     *     {@link TAdresa }
     *     
     */
    public TAdresa getAdresaZaDostavljanje() {
        return adresaZaDostavljanje;
    }

    /**
     * Sets the value of the adresaZaDostavljanje property.
     * 
     * @param value
     *     allowed object is
     *     {@link TAdresa }
     *     
     */
    public void setAdresaZaDostavljanje(TAdresa value) {
        this.adresaZaDostavljanje = value;
    }

    /**
     * Gets the value of the nacinDostavljanja property.
     * 
     * @return
     *     possible object is
     *     {@link TNacinDostavljanja }
     *     
     */
    public TNacinDostavljanja getNacinDostavljanja() {
        return nacinDostavljanja;
    }

    /**
     * Sets the value of the nacinDostavljanja property.
     * 
     * @param value
     *     allowed object is
     *     {@link TNacinDostavljanja }
     *     
     */
    public void setNacinDostavljanja(TNacinDostavljanja value) {
        this.nacinDostavljanja = value;
    }

    /**
     * Gets the value of the povezanaPrijava property.
     * 
     * @return
     *     possible object is
     *     {@link PovezanaPrijava }
     *     
     */
    public PovezanaPrijava getPovezanaPrijava() {
        return povezanaPrijava;
    }

    /**
     * Sets the value of the povezanaPrijava property.
     * 
     * @param value
     *     allowed object is
     *     {@link PovezanaPrijava }
     *     
     */
    public void setPovezanaPrijava(PovezanaPrijava value) {
        this.povezanaPrijava = value;
    }

    /**
     * Gets the value of the zahtevZaPriznanjePravaPrvenstva property.
     * 
     * @return
     *     possible object is
     *     {@link ZahtevZaPriznanjePravaPrvenstva }
     *     
     */
    public ZahtevZaPriznanjePravaPrvenstva getZahtevZaPriznanjePravaPrvenstva() {
        return zahtevZaPriznanjePravaPrvenstva;
    }

    /**
     * Sets the value of the zahtevZaPriznanjePravaPrvenstva property.
     * 
     * @param value
     *     allowed object is
     *     {@link ZahtevZaPriznanjePravaPrvenstva }
     *     
     */
    public void setZahtevZaPriznanjePravaPrvenstva(ZahtevZaPriznanjePravaPrvenstva value) {
        this.zahtevZaPriznanjePravaPrvenstva = value;
    }

}
