//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.01.18 at 06:01:14 PM CET 
//


package com.euprava.euprava.model.a1sertifikat;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Forma_Zapisa.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="Forma_Zapisa"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="Pisana"/&gt;
 *     &lt;enumeration value="Audio"/&gt;
 *     &lt;enumeration value="Vizuelna"/&gt;
 *     &lt;enumeration value="AudioVizuelna"/&gt;
 *     &lt;enumeration value="Opticki Disk"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "Forma_Zapisa")
@XmlEnum
public enum FormaZapisa {

    @XmlEnumValue("Pisana")
    PISANA("Pisana"),
    @XmlEnumValue("Audio")
    AUDIO("Audio"),
    @XmlEnumValue("Vizuelna")
    VIZUELNA("Vizuelna"),
    @XmlEnumValue("AudioVizuelna")
    AUDIO_VIZUELNA("AudioVizuelna"),
    @XmlEnumValue("Opticki Disk")
    OPTICKI_DISK("Opticki Disk");
    private final String value;

    FormaZapisa(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static FormaZapisa fromValue(String v) {
        for (FormaZapisa c: FormaZapisa.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
