//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.01.19 at 05:41:55 PM CET 
//


package com.euprava.euprava.model.a1sertifikat;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.euprava.euprava.model.a1sertifikat package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.euprava.euprava.model.a1sertifikat
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ObrazacA1 }
     * 
     */
    public ObrazacA1 createObrazacA1() {
        return new ObrazacA1();
    }

    /**
     * Create an instance of {@link TDjelo }
     * 
     */
    public TDjelo createTDjelo() {
        return new TDjelo();
    }

    /**
     * Create an instance of {@link TOsoba }
     * 
     */
    public TOsoba createTOsoba() {
        return new TOsoba();
    }

    /**
     * Create an instance of {@link ObrazacA1 .DatumPodnosenja }
     * 
     */
    public ObrazacA1 .DatumPodnosenja createObrazacA1DatumPodnosenja() {
        return new ObrazacA1 .DatumPodnosenja();
    }

    /**
     * Create an instance of {@link ObrazacA1 .Status }
     * 
     */
    public ObrazacA1 .Status createObrazacA1Status() {
        return new ObrazacA1 .Status();
    }

    /**
     * Create an instance of {@link Adresa }
     * 
     */
    public Adresa createAdresa() {
        return new Adresa();
    }

    /**
     * Create an instance of {@link TFizickiPodnosilac }
     * 
     */
    public TFizickiPodnosilac createTFizickiPodnosilac() {
        return new TFizickiPodnosilac();
    }

    /**
     * Create an instance of {@link TPravniPodnosilac }
     * 
     */
    public TPravniPodnosilac createTPravniPodnosilac() {
        return new TPravniPodnosilac();
    }

    /**
     * Create an instance of {@link TStranoDrzavljanstvo }
     * 
     */
    public TStranoDrzavljanstvo createTStranoDrzavljanstvo() {
        return new TStranoDrzavljanstvo();
    }

    /**
     * Create an instance of {@link TDomaceDrzavljanstvo }
     * 
     */
    public TDomaceDrzavljanstvo createTDomaceDrzavljanstvo() {
        return new TDomaceDrzavljanstvo();
    }

    /**
     * Create an instance of {@link TZiviAutor }
     * 
     */
    public TZiviAutor createTZiviAutor() {
        return new TZiviAutor();
    }

    /**
     * Create an instance of {@link TPreminuliAutor }
     * 
     */
    public TPreminuliAutor createTPreminuliAutor() {
        return new TPreminuliAutor();
    }

    /**
     * Create an instance of {@link com.euprava.euprava.model.a1sertifikat.TPodnosilac.Email }
     * 
     */
    public com.euprava.euprava.model.a1sertifikat.TPodnosilac.Email createTPodnosilacEmail() {
        return new com.euprava.euprava.model.a1sertifikat.TPodnosilac.Email();
    }

    /**
     * Create an instance of {@link TDjelo.Naslov }
     * 
     */
    public TDjelo.Naslov createTDjeloNaslov() {
        return new TDjelo.Naslov();
    }

    /**
     * Create an instance of {@link TDjelo.VrstaDjela }
     * 
     */
    public TDjelo.VrstaDjela createTDjeloVrstaDjela() {
        return new TDjelo.VrstaDjela();
    }

    /**
     * Create an instance of {@link TDjelo.FormaZapisa }
     * 
     */
    public TDjelo.FormaZapisa createTDjeloFormaZapisa() {
        return new TDjelo.FormaZapisa();
    }

    /**
     * Create an instance of {@link TDjelo.PodaciAutor }
     * 
     */
    public TDjelo.PodaciAutor createTDjeloPodaciAutor() {
        return new TDjelo.PodaciAutor();
    }

    /**
     * Create an instance of {@link TDjelo.PodaciOriginalnoDjelo }
     * 
     */
    public TDjelo.PodaciOriginalnoDjelo createTDjeloPodaciOriginalnoDjelo() {
        return new TDjelo.PodaciOriginalnoDjelo();
    }

}
