//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.01.10 at 10:30:51 AM CET 
//


package com.euprava.euprava.model.a1sertifikat;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="id"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}long"&gt;
 *               &lt;minInclusive value="1"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="Podnosilac" type="{http://euprava.euprava.com/model/a1Sertifikat}TPodnosilac"/&gt;
 *         &lt;element name="Punomocnik" type="{http://euprava.euprava.com/model/a1Sertifikat}TOsoba" minOccurs="0"/&gt;
 *         &lt;element name="Djelo" type="{http://euprava.euprava.com/model/a1Sertifikat}TDjelo"/&gt;
 *         &lt;element name="Potpis" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="Sifra_Opisa" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="Sifra_Primjera" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="Broj_Prijave" type="{http://www.w3.org/2001/XMLSchema}positiveInteger"/&gt;
 *         &lt;element name="Datum_Podnosenja" type="{http://www.w3.org/2001/XMLSchema}date"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "id",
    "podnosilac",
    "punomocnik",
    "djelo",
    "potpis",
    "sifraOpisa",
    "sifraPrimjera",
    "brojPrijave",
    "datumPodnosenja"
})
@XmlRootElement(name = "obrazacA1")
public class ObrazacA1 {

    protected long id;
    @XmlElement(name = "Podnosilac", required = true)
    protected TPodnosilac podnosilac;
    @XmlElement(name = "Punomocnik")
    protected TOsoba punomocnik;
    @XmlElement(name = "Djelo", required = true)
    protected TDjelo djelo;
    @XmlElement(name = "Potpis", required = true)
    protected String potpis;
    @XmlElement(name = "Sifra_Opisa")
    protected String sifraOpisa;
    @XmlElement(name = "Sifra_Primjera")
    protected String sifraPrimjera;
    @XmlElement(name = "Broj_Prijave", required = true)
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger brojPrijave;
    @XmlElement(name = "Datum_Podnosenja", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar datumPodnosenja;

    /**
     * Gets the value of the id property.
     * 
     */
    public long getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     */
    public void setId(long value) {
        this.id = value;
    }

    /**
     * Gets the value of the podnosilac property.
     * 
     * @return
     *     possible object is
     *     {@link TPodnosilac }
     *     
     */
    public TPodnosilac getPodnosilac() {
        return podnosilac;
    }

    /**
     * Sets the value of the podnosilac property.
     * 
     * @param value
     *     allowed object is
     *     {@link TPodnosilac }
     *     
     */
    public void setPodnosilac(TPodnosilac value) {
        this.podnosilac = value;
    }

    /**
     * Gets the value of the punomocnik property.
     * 
     * @return
     *     possible object is
     *     {@link TOsoba }
     *     
     */
    public TOsoba getPunomocnik() {
        return punomocnik;
    }

    /**
     * Sets the value of the punomocnik property.
     * 
     * @param value
     *     allowed object is
     *     {@link TOsoba }
     *     
     */
    public void setPunomocnik(TOsoba value) {
        this.punomocnik = value;
    }

    /**
     * Gets the value of the djelo property.
     * 
     * @return
     *     possible object is
     *     {@link TDjelo }
     *     
     */
    public TDjelo getDjelo() {
        return djelo;
    }

    /**
     * Sets the value of the djelo property.
     * 
     * @param value
     *     allowed object is
     *     {@link TDjelo }
     *     
     */
    public void setDjelo(TDjelo value) {
        this.djelo = value;
    }

    /**
     * Gets the value of the potpis property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPotpis() {
        return potpis;
    }

    /**
     * Sets the value of the potpis property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPotpis(String value) {
        this.potpis = value;
    }

    /**
     * Gets the value of the sifraOpisa property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSifraOpisa() {
        return sifraOpisa;
    }

    /**
     * Sets the value of the sifraOpisa property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSifraOpisa(String value) {
        this.sifraOpisa = value;
    }

    /**
     * Gets the value of the sifraPrimjera property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSifraPrimjera() {
        return sifraPrimjera;
    }

    /**
     * Sets the value of the sifraPrimjera property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSifraPrimjera(String value) {
        this.sifraPrimjera = value;
    }

    /**
     * Gets the value of the brojPrijave property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getBrojPrijave() {
        return brojPrijave;
    }

    /**
     * Sets the value of the brojPrijave property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setBrojPrijave(BigInteger value) {
        this.brojPrijave = value;
    }

    /**
     * Gets the value of the datumPodnosenja property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDatumPodnosenja() {
        return datumPodnosenja;
    }

    /**
     * Sets the value of the datumPodnosenja property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDatumPodnosenja(XMLGregorianCalendar value) {
        this.datumPodnosenja = value;
    }

}
