//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.12.05 at 03:38:56 по подне CET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://euprava.rs/a1", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.euprava.euprava.model.a1Sertifikat;
