//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.06.09 at 09:24:23 PM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://euprava.euprava.com/model/a1Sertifikat", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.euprava.euprava.model.a1sertifikat;
