//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.01.19 at 05:41:55 PM CET 
//


package com.euprava.euprava.model.a1sertifikat;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TFizicki_Podnosilac complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TFizicki_Podnosilac"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://euprava.euprava.com/model/a1Sertifikat}TPodnosilac"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Podaci_Osoba" type="{http://euprava.euprava.com/model/a1Sertifikat}TOsoba"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TFizicki_Podnosilac", propOrder = {
    "podaciOsoba"
})
public class TFizickiPodnosilac
    extends TPodnosilac
{

    @XmlElement(name = "Podaci_Osoba", required = true)
    protected TOsoba podaciOsoba;

    /**
     * Gets the value of the podaciOsoba property.
     * 
     * @return
     *     possible object is
     *     {@link TOsoba }
     *     
     */
    public TOsoba getPodaciOsoba() {
        return podaciOsoba;
    }

    /**
     * Sets the value of the podaciOsoba property.
     * 
     * @param value
     *     allowed object is
     *     {@link TOsoba }
     *     
     */
    public void setPodaciOsoba(TOsoba value) {
        this.podaciOsoba = value;
    }

}
