//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.12.05 at 03:38:56 по подне CET 
//


package com.euprava.euprava.model.a1Sertifikat;


import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TFizicki_Podnosilac complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TFizicki_Podnosilac">
 *   &lt;complexContent>
 *     &lt;extension base="{http://euprava.rs/a1}TPodnosilac">
 *       &lt;sequence>
 *         &lt;element name="Podaci_Osoba" type="{http://euprava.rs/a1}TOsoba"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TFizicki_Podnosilac", propOrder = {
    "podaciOsoba"
})
public class TFizickiPodnosilac
    extends TPodnosilac
{

    @XmlElement(name = "Podaci_Osoba", required = true)
    protected TOsoba podaciOsoba;

    /**
     * Gets the value of the podaciOsoba property.
     * 
     * @return
     *     possible object is
     *     {@link TOsoba }
     *     
     */
    public TOsoba getPodaciOsoba() {
        return podaciOsoba;
    }

    /**
     * Sets the value of the podaciOsoba property.
     * 
     * @param value
     *     allowed object is
     *     {@link TOsoba }
     *     
     */
    public void setPodaciOsoba(TOsoba value) {
        this.podaciOsoba = value;
    }

}
