//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.12.05 at 03:38:56 по подне CET 
//


package com.euprava.euprava.model.a1Sertifikat;


import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TStrano_Drzavljanstvo complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TStrano_Drzavljanstvo">
 *   &lt;complexContent>
 *     &lt;extension base="{http://euprava.rs/a1}TDrzavljanstvo">
 *       &lt;sequence>
 *         &lt;element name="Broj_Pasosa" type="{http://euprava.rs/a1}TBroj_Pasosa"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TStrano_Drzavljanstvo", propOrder = {
    "brojPasosa"
})
public class TStranoDrzavljanstvo
    extends TDrzavljanstvo
{

    @XmlElement(name = "Broj_Pasosa", required = true)
    protected String brojPasosa;

    /**
     * Gets the value of the brojPasosa property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBrojPasosa() {
        return brojPasosa;
    }

    /**
     * Sets the value of the brojPasosa property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBrojPasosa(String value) {
        this.brojPasosa = value;
    }

}
