//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.01.10 at 10:30:51 AM CET 
//


package com.euprava.euprava.model.a1sertifikat;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TZivi_Autor complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TZivi_Autor"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://euprava.euprava.com/model/a1Sertifikat}TAutor"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Podaci_Autor" type="{http://euprava.euprava.com/model/a1Sertifikat}TOsoba"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TZivi_Autor", propOrder = {
    "podaciAutor"
})
public class TZiviAutor
    extends TAutor
{

    @XmlElement(name = "Podaci_Autor", required = true)
    protected TOsoba podaciAutor;

    /**
     * Gets the value of the podaciAutor property.
     * 
     * @return
     *     possible object is
     *     {@link TOsoba }
     *     
     */
    public TOsoba getPodaciAutor() {
        return podaciAutor;
    }

    /**
     * Sets the value of the podaciAutor property.
     * 
     * @param value
     *     allowed object is
     *     {@link TOsoba }
     *     
     */
    public void setPodaciAutor(TOsoba value) {
        this.podaciAutor = value;
    }

}
