//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.12.05 at 03:38:56 по подне CET 
//


package com.euprava.euprava.model.a1Sertifikat;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Vrsta_Djela.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="Vrsta_Djela">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="Pisano"/>
 *     &lt;enumeration value="Scensko"/>
 *     &lt;enumeration value="Likovno"/>
 *     &lt;enumeration value="Primjenjeno"/>
 *     &lt;enumeration value="Patent"/>
 *     &lt;enumeration value="Informacione Tehnologije"/>
 *     &lt;enumeration value="Naucna Teorija"/>
 *     &lt;enumeration value="Naucna Djelatnost"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "Vrsta_Djela")
@XmlEnum
public enum VrstaDjela {

    @XmlEnumValue("Pisano")
    PISANO("Pisano"),
    @XmlEnumValue("Scensko")
    SCENSKO("Scensko"),
    @XmlEnumValue("Likovno")
    LIKOVNO("Likovno"),
    @XmlEnumValue("Primjenjeno")
    PRIMJENJENO("Primjenjeno"),
    @XmlEnumValue("Patent")
    PATENT("Patent"),
    @XmlEnumValue("Informacione Tehnologije")
    INFORMACIONE_TEHNOLOGIJE("Informacione Tehnologije"),
    @XmlEnumValue("Naucna Teorija")
    NAUCNA_TEORIJA("Naucna Teorija"),
    @XmlEnumValue("Naucna Djelatnost")
    NAUCNA_DJELATNOST("Naucna Djelatnost");
    private final String value;

    VrstaDjela(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static VrstaDjela fromValue(String v) {
        for (VrstaDjela c: VrstaDjela.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
