//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.12.13 at 05:16:31 PM CET 
//


package com.euprava.euprava.model.a1sertifikat;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Vrsta_Djela.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="Vrsta_Djela"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="Pisano"/&gt;
 *     &lt;enumeration value="Scensko"/&gt;
 *     &lt;enumeration value="Likovno"/&gt;
 *     &lt;enumeration value="Primjenjeno"/&gt;
 *     &lt;enumeration value="Patent"/&gt;
 *     &lt;enumeration value="Informacione Tehnologije"/&gt;
 *     &lt;enumeration value="Naucna Teorija"/&gt;
 *     &lt;enumeration value="Naucna Djelatnost"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "Vrsta_Djela")
@XmlEnum
public enum VrstaDjela {

    @XmlEnumValue("Pisano")
    PISANO("Pisano"),
    @XmlEnumValue("Scensko")
    SCENSKO("Scensko"),
    @XmlEnumValue("Likovno")
    LIKOVNO("Likovno"),
    @XmlEnumValue("Primjenjeno")
    PRIMJENJENO("Primjenjeno"),
    @XmlEnumValue("Patent")
    PATENT("Patent"),
    @XmlEnumValue("Informacione Tehnologije")
    INFORMACIONE_TEHNOLOGIJE("Informacione Tehnologije"),
    @XmlEnumValue("Naucna Teorija")
    NAUCNA_TEORIJA("Naucna Teorija"),
    @XmlEnumValue("Naucna Djelatnost")
    NAUCNA_DJELATNOST("Naucna Djelatnost");
    private final String value;

    VrstaDjela(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static VrstaDjela fromValue(String v) {
        for (VrstaDjela c: VrstaDjela.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
