//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.12.12 at 09:28:39 PM CET 
//


package com.euprava.z1.model;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.euprava.z1.model package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.euprava.z1.model
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ZahtevZaPriznanjeZiga }
     * 
     */
    public ZahtevZaPriznanjeZiga createZahtevZaPriznanjeZiga() {
        return new ZahtevZaPriznanjeZiga();
    }

    /**
     * Create an instance of {@link TZig }
     * 
     */
    public TZig createTZig() {
        return new TZig();
    }

    /**
     * Create an instance of {@link ZahtevZaPriznanjeZiga.PlaceneTakse }
     * 
     */
    public ZahtevZaPriznanjeZiga.PlaceneTakse createZahtevZaPriznanjeZigaPlaceneTakse() {
        return new ZahtevZaPriznanjeZiga.PlaceneTakse();
    }

    /**
     * Create an instance of {@link TPrilozi }
     * 
     */
    public TPrilozi createTPrilozi() {
        return new TPrilozi();
    }

    /**
     * Create an instance of {@link TAdresa }
     * 
     */
    public TAdresa createTAdresa() {
        return new TAdresa();
    }

    /**
     * Create an instance of {@link TKontakt }
     * 
     */
    public TKontakt createTKontakt() {
        return new TKontakt();
    }

    /**
     * Create an instance of {@link TFizickoLice }
     * 
     */
    public TFizickoLice createTFizickoLice() {
        return new TFizickoLice();
    }

    /**
     * Create an instance of {@link TPravnoLice }
     * 
     */
    public TPravnoLice createTPravnoLice() {
        return new TPravnoLice();
    }

    /**
     * Create an instance of {@link TZnak }
     * 
     */
    public TZnak createTZnak() {
        return new TZnak();
    }

    /**
     * Create an instance of {@link TTaksa }
     * 
     */
    public TTaksa createTTaksa() {
        return new TTaksa();
    }

    /**
     * Create an instance of {@link TZig.BrojeviKlasaRobe }
     * 
     */
    public TZig.BrojeviKlasaRobe createTZigBrojeviKlasaRobe() {
        return new TZig.BrojeviKlasaRobe();
    }

}
