//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.08.19 at 02:11:40 AM CEST 
//


package com.euprava.z1.model;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.euprava.z1.model package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.euprava.z1.model
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Z1 }
     * 
     */
    public Z1 createZ1() {
        return new Z1();
    }

    /**
     * Create an instance of {@link Kontakt }
     * 
     */
    public Kontakt createKontakt() {
        return new Kontakt();
    }

    /**
     * Create an instance of {@link Lice }
     * 
     */
    public Lice createLice() {
        return new Lice();
    }

    /**
     * Create an instance of {@link Z1 .BrojeviKlasaRobe }
     * 
     */
    public Z1 .BrojeviKlasaRobe createZ1BrojeviKlasaRobe() {
        return new Z1 .BrojeviKlasaRobe();
    }

    /**
     * Create an instance of {@link Z1 .PlaceneTakse }
     * 
     */
    public Z1 .PlaceneTakse createZ1PlaceneTakse() {
        return new Z1 .PlaceneTakse();
    }

    /**
     * Create an instance of {@link Z1 .Prilozi }
     * 
     */
    public Z1 .Prilozi createZ1Prilozi() {
        return new Z1 .Prilozi();
    }

    /**
     * Create an instance of {@link Status }
     * 
     */
    public Status createStatus() {
        return new Status();
    }

    /**
     * Create an instance of {@link Datum }
     * 
     */
    public Datum createDatum() {
        return new Datum();
    }

    /**
     * Create an instance of {@link Adresa }
     * 
     */
    public Adresa createAdresa() {
        return new Adresa();
    }

    /**
     * Create an instance of {@link Kontakt.EPosta }
     * 
     */
    public Kontakt.EPosta createKontaktEPosta() {
        return new Kontakt.EPosta();
    }

}
