//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.06.09 at 11:19:21 PM CEST 
//


package com.euprava.z1.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TPrilozi complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TPrilozi"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="primerak_znaka" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="spisak_robe_i_usluga" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="punomocje" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="generalno_punomocje_ranije_prilozeno" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="punomocje_naknadno_dostavljeno" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="opsti_akt" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="dokaz_o_pravu_prvenstva" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="dokaz_o_uplati_takse" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TPrilozi", propOrder = {
    "primerakZnaka",
    "spisakRobeIUsluga",
    "punomocje",
    "generalnoPunomocjeRanijePrilozeno",
    "punomocjeNaknadnoDostavljeno",
    "opstiAkt",
    "dokazOPravuPrvenstva",
    "dokazOUplatiTakse"
})
public class TPrilozi {

    @XmlElement(name = "primerak_znaka")
    protected String primerakZnaka;
    @XmlElement(name = "spisak_robe_i_usluga")
    protected String spisakRobeIUsluga;
    protected String punomocje;
    @XmlElement(name = "generalno_punomocje_ranije_prilozeno")
    protected String generalnoPunomocjeRanijePrilozeno;
    @XmlElement(name = "punomocje_naknadno_dostavljeno")
    protected String punomocjeNaknadnoDostavljeno;
    @XmlElement(name = "opsti_akt")
    protected String opstiAkt;
    @XmlElement(name = "dokaz_o_pravu_prvenstva")
    protected String dokazOPravuPrvenstva;
    @XmlElement(name = "dokaz_o_uplati_takse")
    protected String dokazOUplatiTakse;

    /**
     * Gets the value of the primerakZnaka property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPrimerakZnaka() {
        return primerakZnaka;
    }

    /**
     * Sets the value of the primerakZnaka property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPrimerakZnaka(String value) {
        this.primerakZnaka = value;
    }

    /**
     * Gets the value of the spisakRobeIUsluga property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSpisakRobeIUsluga() {
        return spisakRobeIUsluga;
    }

    /**
     * Sets the value of the spisakRobeIUsluga property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSpisakRobeIUsluga(String value) {
        this.spisakRobeIUsluga = value;
    }

    /**
     * Gets the value of the punomocje property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPunomocje() {
        return punomocje;
    }

    /**
     * Sets the value of the punomocje property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPunomocje(String value) {
        this.punomocje = value;
    }

    /**
     * Gets the value of the generalnoPunomocjeRanijePrilozeno property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGeneralnoPunomocjeRanijePrilozeno() {
        return generalnoPunomocjeRanijePrilozeno;
    }

    /**
     * Sets the value of the generalnoPunomocjeRanijePrilozeno property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGeneralnoPunomocjeRanijePrilozeno(String value) {
        this.generalnoPunomocjeRanijePrilozeno = value;
    }

    /**
     * Gets the value of the punomocjeNaknadnoDostavljeno property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPunomocjeNaknadnoDostavljeno() {
        return punomocjeNaknadnoDostavljeno;
    }

    /**
     * Sets the value of the punomocjeNaknadnoDostavljeno property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPunomocjeNaknadnoDostavljeno(String value) {
        this.punomocjeNaknadnoDostavljeno = value;
    }

    /**
     * Gets the value of the opstiAkt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOpstiAkt() {
        return opstiAkt;
    }

    /**
     * Sets the value of the opstiAkt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOpstiAkt(String value) {
        this.opstiAkt = value;
    }

    /**
     * Gets the value of the dokazOPravuPrvenstva property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDokazOPravuPrvenstva() {
        return dokazOPravuPrvenstva;
    }

    /**
     * Sets the value of the dokazOPravuPrvenstva property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDokazOPravuPrvenstva(String value) {
        this.dokazOPravuPrvenstva = value;
    }

    /**
     * Gets the value of the dokazOUplatiTakse property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDokazOUplatiTakse() {
        return dokazOUplatiTakse;
    }

    /**
     * Sets the value of the dokazOUplatiTakse property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDokazOUplatiTakse(String value) {
        this.dokazOUplatiTakse = value;
    }

}
