//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.06.10 at 01:26:37 PM CEST 
//


package com.euprava.z1.model;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for TZig complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TZig"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="tip_ziga"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;enumeration value="individualni_zig"/&gt;
 *               &lt;enumeration value="kolektivni_zig"/&gt;
 *               &lt;enumeration value="zig_garancije"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="znak" type="{http://euprava.com/z1/model}TZnak"/&gt;
 *         &lt;element name="brojevi_klasa_robe"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="broj" type="{http://www.w3.org/2001/XMLSchema}positiveInteger"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="zatrazeno_pravo_prvenstva" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="broj_prijave_ziga" type="{http://www.w3.org/2001/XMLSchema}positiveInteger"/&gt;
 *         &lt;element name="datum_podnosenja" type="{http://www.w3.org/2001/XMLSchema}date"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TZig", propOrder = {
    "tipZiga",
    "znak",
    "brojeviKlasaRobe",
    "zatrazenoPravoPrvenstva",
    "brojPrijaveZiga",
    "datumPodnosenja"
})
public class TZig {

    @XmlElement(name = "tip_ziga", required = true)
    protected String tipZiga;
    @XmlElement(required = true)
    protected TZnak znak;
    @XmlElement(name = "brojevi_klasa_robe", required = true)
    protected TZig.BrojeviKlasaRobe brojeviKlasaRobe;
    @XmlElement(name = "zatrazeno_pravo_prvenstva", required = true)
    protected String zatrazenoPravoPrvenstva;
    @XmlElement(name = "broj_prijave_ziga", required = true)
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger brojPrijaveZiga;
    @XmlElement(name = "datum_podnosenja", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar datumPodnosenja;

    /**
     * Gets the value of the tipZiga property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTipZiga() {
        return tipZiga;
    }

    /**
     * Sets the value of the tipZiga property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTipZiga(String value) {
        this.tipZiga = value;
    }

    /**
     * Gets the value of the znak property.
     * 
     * @return
     *     possible object is
     *     {@link TZnak }
     *     
     */
    public TZnak getZnak() {
        return znak;
    }

    /**
     * Sets the value of the znak property.
     * 
     * @param value
     *     allowed object is
     *     {@link TZnak }
     *     
     */
    public void setZnak(TZnak value) {
        this.znak = value;
    }

    /**
     * Gets the value of the brojeviKlasaRobe property.
     * 
     * @return
     *     possible object is
     *     {@link TZig.BrojeviKlasaRobe }
     *     
     */
    public TZig.BrojeviKlasaRobe getBrojeviKlasaRobe() {
        return brojeviKlasaRobe;
    }

    /**
     * Sets the value of the brojeviKlasaRobe property.
     * 
     * @param value
     *     allowed object is
     *     {@link TZig.BrojeviKlasaRobe }
     *     
     */
    public void setBrojeviKlasaRobe(TZig.BrojeviKlasaRobe value) {
        this.brojeviKlasaRobe = value;
    }

    /**
     * Gets the value of the zatrazenoPravoPrvenstva property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getZatrazenoPravoPrvenstva() {
        return zatrazenoPravoPrvenstva;
    }

    /**
     * Sets the value of the zatrazenoPravoPrvenstva property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setZatrazenoPravoPrvenstva(String value) {
        this.zatrazenoPravoPrvenstva = value;
    }

    /**
     * Gets the value of the brojPrijaveZiga property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getBrojPrijaveZiga() {
        return brojPrijaveZiga;
    }

    /**
     * Sets the value of the brojPrijaveZiga property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setBrojPrijaveZiga(BigInteger value) {
        this.brojPrijaveZiga = value;
    }

    /**
     * Gets the value of the datumPodnosenja property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDatumPodnosenja() {
        return datumPodnosenja;
    }

    /**
     * Sets the value of the datumPodnosenja property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDatumPodnosenja(XMLGregorianCalendar value) {
        this.datumPodnosenja = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="broj" type="{http://www.w3.org/2001/XMLSchema}positiveInteger"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "broj"
    })
    public static class BrojeviKlasaRobe {

        @XmlElement(required = true)
        @XmlSchemaType(name = "positiveInteger")
        protected BigInteger broj;

        /**
         * Gets the value of the broj property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getBroj() {
            return broj;
        }

        /**
         * Sets the value of the broj property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setBroj(BigInteger value) {
            this.broj = value;
        }

    }

}
