//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.06.09 at 11:19:21 PM CEST 
//


package com.euprava.z1.model;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="podnosilac" type="{http://euprava.com/z1/model}TLice"/&gt;
 *         &lt;element name="punomocnik" type="{http://euprava.com/z1/model}TLice"/&gt;
 *         &lt;element name="zig" type="{http://euprava.com/z1/model}TZig"/&gt;
 *         &lt;element name="placene_takse"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence maxOccurs="unbounded" minOccurs="0"&gt;
 *                   &lt;element name="taksa" type="{http://euprava.com/z1/model}TTaksa"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="prilozi" type="{http://euprava.com/z1/model}TPrilozi"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "podnosilac",
    "punomocnik",
    "zig",
    "placeneTakse",
    "prilozi"
})
@XmlRootElement(name = "zahtev_za_priznanje_ziga")
public class ZahtevZaPriznanjeZiga {

    @XmlElement(required = true)
    protected TLice podnosilac;
    @XmlElement(required = true)
    protected TLice punomocnik;
    @XmlElement(required = true)
    protected TZig zig;
    @XmlElement(name = "placene_takse", required = true)
    protected ZahtevZaPriznanjeZiga.PlaceneTakse placeneTakse;
    @XmlElement(required = true)
    protected TPrilozi prilozi;

    /**
     * Gets the value of the podnosilac property.
     * 
     * @return
     *     possible object is
     *     {@link TLice }
     *     
     */
    public TLice getPodnosilac() {
        return podnosilac;
    }

    /**
     * Sets the value of the podnosilac property.
     * 
     * @param value
     *     allowed object is
     *     {@link TLice }
     *     
     */
    public void setPodnosilac(TLice value) {
        this.podnosilac = value;
    }

    /**
     * Gets the value of the punomocnik property.
     * 
     * @return
     *     possible object is
     *     {@link TLice }
     *     
     */
    public TLice getPunomocnik() {
        return punomocnik;
    }

    /**
     * Sets the value of the punomocnik property.
     * 
     * @param value
     *     allowed object is
     *     {@link TLice }
     *     
     */
    public void setPunomocnik(TLice value) {
        this.punomocnik = value;
    }

    /**
     * Gets the value of the zig property.
     * 
     * @return
     *     possible object is
     *     {@link TZig }
     *     
     */
    public TZig getZig() {
        return zig;
    }

    /**
     * Sets the value of the zig property.
     * 
     * @param value
     *     allowed object is
     *     {@link TZig }
     *     
     */
    public void setZig(TZig value) {
        this.zig = value;
    }

    /**
     * Gets the value of the placeneTakse property.
     * 
     * @return
     *     possible object is
     *     {@link ZahtevZaPriznanjeZiga.PlaceneTakse }
     *     
     */
    public ZahtevZaPriznanjeZiga.PlaceneTakse getPlaceneTakse() {
        return placeneTakse;
    }

    /**
     * Sets the value of the placeneTakse property.
     * 
     * @param value
     *     allowed object is
     *     {@link ZahtevZaPriznanjeZiga.PlaceneTakse }
     *     
     */
    public void setPlaceneTakse(ZahtevZaPriznanjeZiga.PlaceneTakse value) {
        this.placeneTakse = value;
    }

    /**
     * Gets the value of the prilozi property.
     * 
     * @return
     *     possible object is
     *     {@link TPrilozi }
     *     
     */
    public TPrilozi getPrilozi() {
        return prilozi;
    }

    /**
     * Sets the value of the prilozi property.
     * 
     * @param value
     *     allowed object is
     *     {@link TPrilozi }
     *     
     */
    public void setPrilozi(TPrilozi value) {
        this.prilozi = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence maxOccurs="unbounded" minOccurs="0"&gt;
     *         &lt;element name="taksa" type="{http://euprava.com/z1/model}TTaksa"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "taksa"
    })
    public static class PlaceneTakse {

        protected List<TTaksa> taksa;

        /**
         * Gets the value of the taksa property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the taksa property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getTaksa().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link TTaksa }
         * 
         * 
         */
        public List<TTaksa> getTaksa() {
            if (taksa == null) {
                taksa = new ArrayList<TTaksa>();
            }
            return this.taksa;
        }

    }

}
